name: Build APKs
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3
      - uses: gradle/actions/setup-gradle@v4
      - name: Litsenziyalarni qabul qilish
        run: yes | sdkmanager --licenses > /dev/null

      - name: 1) Target APK ni yig'ish
        run: cd target && gradle assembleDebug --stacktrace

      - name: 2) Target APK ni Evader assets ga qo'yish
        run: |
          mkdir -p app/src/main/assets
          cp target/app/build/outputs/apk/debug/app-debug.apk app/src/main/assets/target.apk
          cp target/app/build/outputs/apk/debug/app-debug.apk app/src/main/assets/split.apk

      - name: 3) EvaderTest APK ni yig'ish
        run: gradle assembleDebug --stacktrace

      - name: 4) Ikkala APK ni saqlash
        uses: actions/upload-artifact@v4
        with:
          name: EvaderTest-barcha-apk
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            target/app/build/outputs/apk/debug/app-debug.apk
